### ISSUE TITLE
Need a way to make more than one perturbation in the same sentence

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#109]
Example: When testing for swap entities, I want to be able to have multiple copies of a sentence with different entities swapped. How do I do this in the config file?

Currently "I live in Boston" -> "I live in Mumbai"

We need a parameter to control and have multiple duplicates if desired: "I live in Boston" -> "I live in Mumbai", "I live in Paris", "I live in New York", "I live in London"

Default should be no duplicates (only 1 version of the sentence)

**Comment by dcecchini** [comment]
We need to perform experiments to check whether the number of tests applied to common datasets are enough. If it is too small, then we can create new tests by swapping them with different names.
