### ISSUE TITLE
Improve accuracy of underlying gender classifier

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#153]

**Comment by dcecchini** [comment]
There are a few issues here:

- Low accuracy
- It is US-biased 
- It depends on the transformers library (we want to remove transformers, johnsnowlabs, spacy, etc. from the dependencies)

Should we use rules-based model or implement a ML one?

**Comment by JulesBelveze** [comment]
Publish the current model to HF hub
