### ISSUE TITLE
Add disinformation tests

### ISSUE THREAD

**Issue by dcecchini** [JohnSnowLabs/langtest#530]
Check metrics from [HELM](https://crfm.stanford.edu/helm/latest/?group=core_scenarios#Disinformation%20metrics). 

Are there curated datasets available?

Metrics:
- Self-BLEU
- Entropy (Monte Carlo)

**Comment by ArshaanNazir** [comment]
https://github.com/stanford-crfm/helm/blob/main/src/helm/benchmark/scenarios/disinformation_scenario.py

**Comment by RakshitKhajuria** [comment]
@dcecchini, 

After going through the paper [Truth, Lies, and Automation](https://cset.georgetown.edu/wp-content/uploads/CSET-Truth-Lies-and-Automation.pdf) and the [link ](https://github.com/stanford-crfm/helm/blob/main/src/helm/benchmark/scenarios/disinformation_scenario.py)provided above

These were my findings:

1. They are using two DisinformationScenario -> Narrative Reiteration and Narrative Wedging
2. In Narrative Reiteration test - It tests the ability of models to generate new headlines that promote a given narrative (whether the narrative is true or fase). 
3. With little effort on GPT-3 performed quite well, easily generating tweet-length messages that fit the desired theme and did not directly repeat the examples we provided. It can produce similar quality of outputs with similarly low levels of effort for almost any topic or argument whether it is a propaganda or not.

**If given GPT-3 inputs and outputs for climate denialist tweets how are we going to evaluate the results if they are true or not can you provide us with an example, it would be helpful...**
