### ISSUE TITLE
Choose backend for custom models

### ISSUE THREAD

**Issue by dcecchini** [JohnSnowLabs/langtest#541]
We have implemented two models to be used in our tests: Gender Classifier and Toxicity. 

Gender Classifier is implemented in transformers, while toxicity is available on the `evaluate` library (transformers). 

We need to choose one provider and stick to it, as the number of models that may be implemented can increase (e.g., to test misinformation, NLI).

One candidate is to use the transformers library,

**Comment by JulesBelveze** [comment]
@dcecchini @ArshaanNazir please let me know what you think but here are my takeaways.

I think it should stick to having a dependency with `transformers` for the models that need to be used in our tests:
- ideally we would go rule based but I can already some limitations to it: impractical for multilingual cases, should work decently for the two use cases we currently have but it might perform poorly in the future.
- Thinking of the embedding similarity metric we talked about we will need a DL model.
- We can have the `transformers` dependency` optional and have the user to manually install it if they use some of the tests requiring it
