### ISSUE TITLE
Add poetry to manage dependencies, etc.

### ISSUE THREAD

**Issue by dcecchini** [JohnSnowLabs/langtest#557]
We can use it to manage package dependencies and add other tasks, e.g., testing for documentation, linting, code formatting, etc.

**Comment by JulesBelveze** [comment]
1. Add poetry as a dependency manager and make third party packages optional (if I'm not wrong one can install optional dependencies as `group` in poetry)
2. Add poetry build and deploy the GH workflows
3. Add testing, linting and formatting as poetry tasks
4. Add type checking as poetry task
