### ISSUE TITLE
Add support for templatic augmentation

### ISSUE THREAD

**Issue by JulesBelveze** [JohnSnowLabs/langtest#602]
Given a template that represents the pattern and the distribution of the entities, generate new sentences using the entities in the original conll

**Comment by chakravarthik27** [comment]
Hi @JulesBelveze 

For templates are in CONLL format only, right? bcoz, without labels for words form templatic sentences. we can't generate a conll file after augmentation.

For example:

template:  The patient takes an {x} drug to cure the {y}disease.

from this template, there is a lack of labels for **the**, **patient**, **takes** .... etc

So, I suggest that users provide in conll format for templates.

**Comment by JulesBelveze** [comment]
@chakravarthik27 yeah I think that's the way to go ! 🤓
