### ISSUE TITLE
Update All Data Augmentation Functionalities on Website

### ISSUE THREAD

**Issue by ArshaanNazir** [JohnSnowLabs/langtest#688]
Update all data augmentation functionalities ( custom_proportions, templatic_augmentation etc) here on webpage and provide necessary notebook links as we did for benchmark datasets.

Add sections:

- custom_proportions
- templatic_augmentation  etc

![Image](https://user-images.githubusercontent.com/71844877/257728959-d00ce5d4-66c1-42e9-8617-70c2a6b53635.png)

**Comment by RakshitKhajuria** [comment]
@ArshaanNazir 
Updated it in this pr https://github.com/JohnSnowLabs/langtest/pull/653
