### ISSUE TITLE
Add new Factuality test

### ISSUE THREAD

**Issue by dcecchini** [JohnSnowLabs/langtest#748]
Follow this approach: [Llama 2 vs GPT](https://www.anyscale.com/blog/llama-2-is-about-as-factually-accurate-as-gpt-4-for-summaries-and-is-30x-cheaper). 

The idea is to give the LLM model two texts, one which is factual and accurate and one that is not, and the model should say which one is the factual one. 

Check the link to see if the model data is available (prompt and texts), otherwise create an issue to build this kind of data in future.

**Comment by RakshitKhajuria** [comment]
Factuality test Data: [Dataset](https://github.com/anyscale/factuality-eval/blob/main/resources/datasets/val_sentence_pairs.json)
Factuality test prompts used for experiment: [Prompts used](https://github.com/anyscale/factuality-eval/tree/main/resources/environments/answer_first/prompts)
Evaluation Notebook : [Notebook](https://github.com/anyscale/factuality-eval/blob/main/factuality_evaluation.ipynb)
