### ISSUE TITLE
PretrainedCustomModel lacks predict_raw preventing fairness and performance tests

### ISSUE THREAD

**Issue by simonamaggio** [JohnSnowLabs/langtest#897]
**Describe the bug**
Custom classifiers are loaded into the langetst `PretrainedModelForTextClassification` which lacks a `predict_raw` function. In [the code](https://github.com/JohnSnowLabs/langtest/blob/a3f89b21a726a6c09fdb70259d5687f944ebb1f7/langtest/transform/__init__.py#L906C21-L906C21), the faireness and performance tests require this call and raise an `AttributeError: 'PretrainedModelForTextClassification' object has no attribute 'predict_raw'`.

This is true for any custom models as they all inherit from [`PretrainedCustomModel`](https://github.com/JohnSnowLabs/langtest/blob/a3f89b21a726a6c09fdb70259d5687f944ebb1f7/langtest/modelhandler/custom_modelhandler.py#L9C7-L9C28) which has no such function.

**To Reproduce**
1. Take a custom text-classifier based on an LLM, here prod_classifier (mine was in-context learnt from `EleutherAI/gpt-neo-1.3B` using the `huggingface-inference-api` hub, but I don't think it's important)
2. Generate and Run the 'fairness' or 'accuracy' tests:
```
config = {
  'tests': {
    'fairness': {
      'min_gender_f1_score': {'min_score': 0.75},
    }
   }
}

harness = Harness(task="text-classification",
                  model={"model":prod_classifier,"hub":"custom"}, 
                  data={"data_source": mydataset_path},
                  config=config)


harness.data = harness.data[:10]

harness.generate()

harness.run()
```

**Comment by chakravarthik27** [comment]
Thank you very much, @simonamaggio! We are aware of the reported issue and will address it in a future release. Your patience is much appreciated.
